-- 1. Tabelul pentru Clienți
CREATE TABLE CLIENTI (
    ID_CLIENT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUME VARCHAR2(50) NOT NULL,
    PRENUME VARCHAR2(50) NOT NULL,
    TELEFON VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    CNP VARCHAR2(13) NOT NULL,
    DATA_INREGISTRARE DATE DEFAULT SYSDATE
);

-- 2. Tabelul pentru Servicii Extra
CREATE TABLE SERVICII_EXTRA (
    ID_SERVICIU NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DENUMIRE VARCHAR2(100) NOT NULL,
    PRET NUMBER(8,2) NOT NULL
);

-- Populam opțiunile de pe site
INSERT INTO SERVICII_EXTRA (DENUMIRE, PRET) VALUES ('Șampanie de bun venit', 150);
INSERT INTO SERVICII_EXTRA (DENUMIRE, PRET) VALUES ('Selecție Vin Premium', 100);
INSERT INTO SERVICII_EXTRA (DENUMIRE, PRET) VALUES ('Decor floral romantic', 200);
COMMIT;

-- 3. Tabelul pentru Rezervări
CREATE TABLE REZERVARI (
    ID_REZERVARE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENT NUMBER NOT NULL,
    DATA_CHECKIN DATE NOT NULL,
    DATA_CHECKOUT DATE NOT NULL,
    SERVICII_EXTRA_ALESE VARCHAR2(250),
    PRET_TOTAL NUMBER(8,2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'CONFIRMATA',
    DATA_CREARE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_REZERVARE_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTI(ID_CLIENT)
);
-- 1. Stergere tabele vechi (daca exista deja)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE REZERVARI CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SERVICII_EXTRA CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CLIENTI CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 2. Tabelul pentru Clienti + Secventa + Trigger (Auto-Increment)
CREATE TABLE CLIENTI (
    ID_CLIENT NUMBER PRIMARY KEY,
    NUME VARCHAR2(50) NOT NULL,
    PRENUME VARCHAR2(50) NOT NULL,
    TELEFON VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    CNP VARCHAR2(13) NOT NULL,
    DATA_INREGISTRARE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_CLIENTI START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CLIENTI_ID
BEFORE INSERT ON CLIENTI
FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENT IS NULL THEN
        SELECT SEQ_CLIENTI.NEXTVAL INTO :NEW.ID_CLIENT FROM DUAL;
    END IF;
END;
/

-- 3. Tabelul pentru Servicii Extra + Secventa + Trigger
CREATE TABLE SERVICII_EXTRA (
    ID_SERVICIU NUMBER PRIMARY KEY,
    DENUMIRE VARCHAR2(100) NOT NULL,
    PRET NUMBER(8,2) NOT NULL
);

CREATE SEQUENCE SEQ_SERVICII_EXTRA START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_SERVICII_EXTRA_ID
BEFORE INSERT ON SERVICII_EXTRA
FOR EACH ROW
BEGIN
    IF :NEW.ID_SERVICIU IS NULL THEN
        SELECT SEQ_SERVICII_EXTRA.NEXTVAL INTO :NEW.ID_SERVICIU FROM DUAL;
    END IF;
END;
/

-- 4. Inserare opțiuni extra
INSERT INTO SERVICII_EXTRA (DENUMIRE, PRET) VALUES ('Șampanie de bun venit', 150);
INSERT INTO SERVICII_EXTRA (DENUMIRE, PRET) VALUES ('Selecție Vin Premium', 100);
INSERT INTO SERVICII_EXTRA (DENUMIRE, PRET) VALUES ('Decor floral romantic', 200);
COMMIT;

-- 5. Tabelul pentru Rezervari + Secventa + Trigger
CREATE TABLE REZERVARI (
    ID_REZERVARE NUMBER PRIMARY KEY,
    ID_CLIENT NUMBER NOT NULL,
    DATA_CHECKIN DATE NOT NULL,
    DATA_CHECKOUT DATE NOT NULL,
    SERVICII_EXTRA_ALESE VARCHAR2(250),
    PRET_TOTAL NUMBER(8,2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'CONFIRMATA',
    DATA_CREARE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_REZERVARE_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTI(ID_CLIENT)
);

CREATE SEQUENCE SEQ_REZERVARI START WITH 1 INCREMENT BY 1;



CREATE OR REPLACE TRIGGER TRG_REZERVARI_ID
BEFORE INSERT ON REZERVARI
FOR EACH ROW
BEGIN
    IF :NEW.ID_REZERVARE IS NULL THEN
        SELECT SEQ_REZERVARI.NEXTVAL INTO :NEW.ID_REZERVARE FROM DUAL;
    END IF;
END;
/
DESCRIBE clienti;
DESCRIBE rezervari;
DESCRIBE servicii_extra;

SELECT * FROM clienti;
SELECT * FROM rezervari;
SELECT * FROM servicii_extra;